<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Divalto
 * @package    Divalto_Customer
 * @subpackage view
 * @author SySwatis (Stéphane JIMENEZ)
 * @copyright Copyright (c) 2020 SySwatis (http://www.syswatis.com)
 */
?>
<?php if($block->getOutstanding()!==null && $block->getOutstanding()==0) :  ?>
<div class="block global message error" role="alert" aria-live = "assertive">
	<p><?= $block->getOutstandingMessage() ?></p>
</div>
<?php endif ?>