<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Divalto
 * @package    Divalto_Customer
 * @subpackage view
 * @author SySwatis (Stéphane JIMENEZ)
 * @copyright Copyright (c) 2020 SySwatis (http://www.syswatis.com)
 */
?>
<?php  $invoiceList = $block->getInvoiceList(); ?>
	<div class="block">
		<p><?= __('Your invoices over %1 month(s)','3') ?></p>
		<p><?= __('Customers') ?> : <?= $block->getGroupCode() ?></p>
<?php if( is_array($invoiceList) ) : ?>
	
	<ul>
<?php foreach ($invoiceList as $filename) : ?>
	<li><a href="<?= $block->getBaseUrl().$filename ?>"><?= basename($filename) ?></a></li>
<?php endforeach ?>
	</ul>
<?php else : ?>
<p><?= __('No invoices yet') ?></p>
<?php endif ?>
	</div>