<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Divalto
 * @package    Divalto_Customer
 * @subpackage view
 * @author SySwatis (Stéphane JIMENEZ)
 * @copyright Copyright (c) 2020 SySwatis (http://www.syswatis.com)
 */
?>
<legend class="legend"><span><?= $block->escapeHtmlAttr(__('Administrative Information')) ?></span></legend>
<div class="field legal-form required">
    <label class="label" for="siret">
      <span><?= $block->escapeHtml(__('Legal Form')) ?></span>
    </label>
    <div class="control">
       <select id="legal_form" name="legal_form" title="<?= $block->escapeHtmlAttr(__('Legal Form')) ?>" class="validate-select legal_form" data-validate="{required:true}">
            <option value=""><?= $block->escapeHtml(__('Please select')) ?></option><?= $block->getLegalFormHtmlOptions() ?><option value="Other"><?= $block->escapeHtml(__('Other')) ?></option>
        </select>
    </div>
</div>
<div class="field company-name required">
    <label class="label" for="company-name">
      <span><?= $block->escapeHtml(__('Company Name')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="company-name" id="company_name" value="" title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>" class="input-text" data-validate="{required:true, company-name:true}">
    </div>
</div>
<div class="field siret required">
    <label class="label" for="siret">
      <span><?= $block->escapeHtml(__('Siret')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="siret" id="siret" value="" title="<?= $block->escapeHtmlAttr(__('Siret')) ?>" class="input-text" data-validate="{required:true, siret:true}">
    </div>
</div>
<div class="field ape required">
    <label class="label" for="ape">
      <span><?= $block->escapeHtml(__('Code Ape')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="ape" id="ape" value="" title="<?= $block->escapeHtmlAttr(__('Code Ape')) ?>" class="input-text" data-validate="{required:true, ape:true}">
    </div>
</div>
<script type="text/x-magento-init">
   {
       "*": {
           "divaltoMethod": {}
       }
   }
</script>