<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Divalto
 * @package    Divalto_Customer
 * @subpackage view
 * @author SySwatis (Stéphane JIMENEZ)
 * @copyright Copyright (c) 2020 SySwatis (http://www.syswatis.com)
 */
?>
<legend class="legend"><span><?= $block->escapeHtmlAttr(__('Administrative Information')) ?></span></legend>
<div class="field legal-form required">
    <label class="label" for="siret">
      <span><?= $block->escapeHtml(__('Legal Form')) ?></span>
    </label>
    <div class="control">
       <select id="legal_form" name="legal_form" title="<?= $block->escapeHtmlAttr(__('Legal Form')) ?>" class="validate-select legal_form" data-validate="{required:true}">
            <option value=""><?= $block->escapeHtml(__('Please select')) ?></option><?= $block->getLegalFormHtmlOptions() ?><option value="Other"><?= $block->escapeHtml(__('Other')) ?></option>
        </select>
    </div>
</div>
<div class="field company_name required">
    <label class="label" for="company_name">
      <span><?= $block->escapeHtml(__('Company Name')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="company_name" id="company_name" value="" title="<?= $block->escapeHtmlAttr(__('Company Name')) ?>" class="input-text" data-validate="{required:true}">
    </div>
</div>
<!-- <div class="field siret required">
    <label class="label" for="siret">
      <span><?= $block->escapeHtml(__('Siret')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="siret" id="siret" value="" title="<?= $block->escapeHtmlAttr(__('Siret')) ?>" class="input-text" data-validate="{required:true, siret:true,'remote':'<?php echo $this->getUrl('divalto/validate/siretbyvat', ['_secure' => true]); ?>'}">
    </div>
</div> 
<div class="field ape required">
    <label class="label" for="ape">
      <span><?= $block->escapeHtml(__('Code Ape')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="ape" id="ape" value="" title="<?= $block->escapeHtmlAttr(__('Code Ape')) ?>" class="input-text" data-validate="{required:true, ape:true}">
    </div>
</div>
-->
<div class="field siret required">
    <label class="label" for="taxvat">
      <span><?= $block->escapeHtml(__('VAT number')) ?></span>
    </label>
    <div class="control">
<?php if($block->validateVat()==1) : ?>
      <input type="text" name="taxvat" id="taxvat" value="" title="<?= $block->escapeHtmlAttr(__('VAT number')) ?>" class="input-text" data-validate="{required:true,'remote':'<?php echo $this->getUrl('divalto/validate/vat', ['_secure' => true]); ?>'}">
<?php else : ?>
      <input type="text" name="taxvat" id="taxvat" value="" title="<?= $block->escapeHtmlAttr(__('VAT number')) ?>" class="input-text" data-validate="{required:true}">
<?php endif ?>
    </div>
</div>
<div class="field phone_number required">
   <label class="label" for="phone_number">
       <span><?= $block->escapeHtml(__('Phone')) ?></span>
   </label>
   <div class="control">
       <input type="text" name="phone_number" id="phone_number" value="" title="<?= $block->escapeHtmlAttr(__('Phone number')) ?>" class="input-text" data-validate="{required:true}">
   </div>
</div>

<script type="text/x-magento-init">
   {
       "*": {
           "divaltoMethod": {}
       }
   }
</script>