<legend class="legend"><span><?= $block->escapeHtmlAttr(__('Administrative Information')) ?></span></legend>
<div class="field legal-form required">
    <label class="label" for="siret">
      <span><?= $block->escapeHtml(__('Legal Form')) ?></span>
    </label>
    <div class="control">
       <select id="legal_form" name="legal_form" title="<?= $block->escapeHtmlAttr(__('Legal Form')) ?>" class="validate-select legal_form" data-validate="{required:true}">
            <option value=""><?= $block->escapeHtml(__('Please select')) ?></option><?= $block->getLegalFormHtmlOptions() ?><option value="Other"><?= $block->escapeHtml(__('Other')) ?></option>
        </select>
    </div>
</div>
<div class="field siret required">
    <label class="label" for="siret">
      <span><?= $block->escapeHtml(__('Siret')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="siret" id="siret" value="" title="<?= $block->escapeHtmlAttr(__('Siret')) ?>" class="input-text" data-validate="{required:true, siret:true}">
    </div>
</div>
<div class="field ape required">
    <label class="label" for="ape">
      <span><?= $block->escapeHtml(__('Code Ape')) ?></span>
    </label>
    <div class="control">
       <input type="text" name="ape" id="ape" value="" title="<?= $block->escapeHtmlAttr(__('Code Ape')) ?>" class="input-text" data-validate="{required:true, ape:true}">
    </div>
</div>
<script type="text/x-magento-init">
   {
       "*": {
           "divaltoMethod": {}
       }
   }
</script>