<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 */

/**
 * @category   Divalto
 * @package    Divalto_Customer
 * @subpackage view
 * @author SySwatis (Stéphane JIMENEZ)
 * @copyright Copyright (c) 2020 SySwatis (http://www.syswatis.com)
 */
?>
<div class="block">
	<div class="block-title initial"><strong><?= __('Outstanding') ?></strong></div>
<?php if($block->getOutstanding()>0) :  ?>
	<p><?= __('You can order and pay online') ?></p>
<?php else : ?>
	<p><?= __('You can only order, payment online not authorized') ?></p>
<?php endif ?>
</div>